# Generated by Django 4.0.4 on 2022-04-29 17:55

import core.models
from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moeda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome_moeda', models.CharField(max_length=15)),
                ('preco_moeda', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Preço')),
                ('logo_moeda', stdimage.models.StdImageField(upload_to=core.models.get_file_path, verbose_name='Logo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
