# Generated by Django 4.0.4 on 2022-05-03 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Moeda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome_moeda', models.CharField(max_length=10, verbose_name='Moeda')),
            ],
            options={
                'verbose_name': 'Moeda',
                'verbose_name_plural': 'Moedas',
            },
        ),
        migrations.CreateModel(
            name='Moeda_Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('quantidade_reais_compra', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Quantidade (R$)')),
                ('status', models.CharField(choices=[('active', 'Ativo na Conta'), ('waiting', 'Venda Solicitada'), ('sold', 'Vendido'), ('refunded', 'Reembolsado')], default='active', max_length=100, verbose_name='Status')),
                ('moeda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.moeda', verbose_name='Moeda')),
            ],
            options={
                'verbose_name': 'Moeda_Usuario',
                'verbose_name_plural': 'Moedas_Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Solicitacao_Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome_venda', models.CharField(default='c6d866f9-487a-418f-b6bc-53a813379d64', max_length=100, verbose_name='Nome Venda')),
                ('status_venda', models.CharField(choices=[('waiting', 'Solicitado'), ('done', 'Vendido'), ('canceled', 'Cancelado')], default='waiting', max_length=100, verbose_name='Status')),
                ('cliente_venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('posse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.moeda_usuario', verbose_name='Posse Escolhida')),
            ],
            options={
                'verbose_name': 'Solicitação de Venda',
                'verbose_name_plural': 'Solicitações de Venda',
            },
        ),
        migrations.CreateModel(
            name='Solicitacao_Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome_compra', models.CharField(default='f13a88f2-24de-4132-b7d6-f5702b8f266b', editable=False, max_length=100, verbose_name='Nome Compra')),
                ('quantidade_reais_compra', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Quantidade (R$)')),
                ('status_compra', models.CharField(choices=[('waiting', 'Esperando Pagamento'), ('done', 'Pagamento Confirmado'), ('canceled', 'Cancelado')], default=('waiting', 'Esperando Pagamento'), max_length=100, verbose_name='Status')),
                ('cliente_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('moeda_compra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.moeda', verbose_name='Moeda Escolhida')),
            ],
            options={
                'verbose_name': 'Solicitação de Compra',
                'verbose_name_plural': 'Solicitações de Compra',
            },
        ),
        migrations.AddField(
            model_name='moeda_usuario',
            name='solicitacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.solicitacao_compra', verbose_name='Compra'),
        ),
        migrations.AddField(
            model_name='moeda_usuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
