# Generated by Django 4.0.4 on 2022-05-03 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao_compra',
            name='nome_compra',
            field=models.CharField(default='2c5e5a1c-4a88-4789-8687-355ea85e2afe', editable=False, max_length=100, verbose_name='Nome Compra'),
        ),
        migrations.AlterField(
            model_name='solicitacao_venda',
            name='nome_venda',
            field=models.CharField(default='ca04face-38ad-41a7-af89-cb5da34e0ad5', max_length=100, verbose_name='Nome Venda'),
        ),
        migrations.CreateModel(
            name='Solicitacao_Deposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('quantidade_reais_deposito', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Quantidade (R$)')),
                ('status_deposito', models.CharField(choices=[('waiting', 'Esperando Pagamento'), ('done', 'Pagamento Confirmado'), ('canceled', 'Cancelado')], default=('waiting', 'Esperando Pagamento'), max_length=100, verbose_name='Status')),
                ('cliente_deposito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Solicitação de Deposito',
                'verbose_name_plural': 'Solicitações de Deposito',
            },
        ),
    ]
