# Generated by Django 4.0.4 on 2022-05-01 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitacao_compra',
            options={'verbose_name': 'Solicitação de Compra', 'verbose_name_plural': 'Solicitações de Compras'},
        ),
        migrations.AlterField(
            model_name='solicitacao_compra',
            name='nome_compra',
            field=models.CharField(default='5643291f-4be5-46f6-8d17-badee8c14539', max_length=100, verbose_name='Nome Compra'),
        ),
    ]
