# Generated by Django 4.0.4 on 2022-05-04 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saque',
            name='nome_saque',
            field=models.CharField(default='e02362ba-3d26-4033-86cb-7a0357f48f9e', max_length=100, verbose_name='Nome Saque'),
        ),
        migrations.AlterField(
            model_name='saque',
            name='status_saque',
            field=models.TextField(choices=[('waiting', 'Solicitado'), ('done', 'Efetuado'), ('canceled', 'Cancelado')], default='waiting', max_length=100, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='solicitacao_compra',
            name='nome_compra',
            field=models.CharField(default='1fc6eae8-513f-4399-b4b2-9a8c41c1b295', editable=False, max_length=100, verbose_name='Nome Compra'),
        ),
        migrations.AlterField(
            model_name='solicitacao_venda',
            name='nome_venda',
            field=models.CharField(default='35fd5e7b-a390-4392-9148-4b1f6a8258ac', max_length=100, verbose_name='Nome Venda'),
        ),
    ]
