# Generated by Django 4.0.4 on 2022-05-01 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_alter_solicitacao_compra_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitacao_compra',
            options={'verbose_name': 'Solicitação de Compra', 'verbose_name_plural': 'Solicitações de Compra'},
        ),
        migrations.AlterField(
            model_name='solicitacao_compra',
            name='nome_compra',
            field=models.CharField(default='688712ee-3d81-4b94-a1ab-cbd0093d6cf0', max_length=100, verbose_name='Nome Compra'),
        ),
        migrations.CreateModel(
            name='Solicitacao_Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome_venda', models.CharField(default='99a599f2-34ac-41ad-bc9d-30e1039c4868', max_length=100, verbose_name='Nome Venda')),
                ('status_venda', models.CharField(choices=[('waiting', 'Solicitado'), ('done', 'Realizado'), ('canceled', 'Cancelado')], default=('waiting', 'Solicitado'), max_length=100, verbose_name='Status')),
                ('cliente_venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('moeda_venda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.moeda_usuario', verbose_name='Moeda Escolhida')),
            ],
            options={
                'verbose_name': 'Solicitação de Venda',
                'verbose_name_plural': 'Solicitações de Venda',
            },
        ),
    ]
