# Generated by Django 4.0.4 on 2022-04-30 00:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_moeda_capitalizacao_mercado_moeda_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('moeda_compra', models.CharField(max_length=50, verbose_name='Moeda')),
                ('valor_moeda_compra', models.DecimalField(decimal_places=8, max_digits=8)),
                ('quantidade_moeda_compra', models.DecimalField(decimal_places=8, max_digits=8)),
                ('status_compra', models.CharField(choices=[('waiting', 'Esperando Pagamento'), ('done', 'Pagamento Confirmado'), ('canceled', 'Cancelado')], default=('waiting', 'Esperando Pagamento'), max_length=20, verbose_name='Status')),
                ('cliente_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
            },
        ),
        migrations.DeleteModel(
            name='Moeda',
        ),
    ]
