# Generated by Django 4.0.4 on 2022-05-03 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_alter_solicitacao_compra_nome_compra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao_compra',
            name='nome_compra',
            field=models.CharField(default='9903d71c-88c0-44b0-8df0-44fd2cf23fa3', editable=False, max_length=100, verbose_name='Nome Compra'),
        ),
        migrations.AlterField(
            model_name='solicitacao_deposito',
            name='cliente_deposito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='solicitacao_venda',
            name='nome_venda',
            field=models.CharField(default='2f87a190-8245-465b-b4d7-d3971dfdcfd7', max_length=100, verbose_name='Nome Venda'),
        ),
    ]
