# Generated by Django 4.0.4 on 2022-05-04 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_saque_nome_saque_alter_saque_status_saque_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saque',
            name='destino_saque',
            field=models.TextField(max_length=1000, verbose_name='Descrição do Saque'),
        ),
        migrations.AlterField(
            model_name='saque',
            name='nome_saque',
            field=models.CharField(default='545bd335-786b-4e8c-a0d6-4145c1a32e79', max_length=100, verbose_name='Nome Saque'),
        ),
        migrations.AlterField(
            model_name='saque',
            name='status_saque',
            field=models.CharField(choices=[('waiting', 'Solicitado'), ('done', 'Efetuado'), ('canceled', 'Cancelado')], default='waiting', max_length=100, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='solicitacao_compra',
            name='nome_compra',
            field=models.CharField(default='4b776540-96c5-45f5-b62d-4cdec8328345', editable=False, max_length=100, verbose_name='Nome Compra'),
        ),
        migrations.AlterField(
            model_name='solicitacao_venda',
            name='nome_venda',
            field=models.CharField(default='7d375377-0b7f-4c7e-bacf-9c1c1b71e41c', max_length=100, verbose_name='Nome Venda'),
        ),
    ]
