# Generated by Django 4.0.4 on 2022-04-30 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_compra_delete_moeda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='quantidade_moeda_compra',
            field=models.DecimalField(decimal_places=8, max_digits=16),
        ),
        migrations.AlterField(
            model_name='compra',
            name='valor_moeda_compra',
            field=models.DecimalField(decimal_places=8, max_digits=16),
        ),
    ]
