# Generated by Django 4.0.4 on 2022-05-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_solicitacao_compra_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao_compra',
            name='nome_compra',
            field=models.CharField(default='8d89e37d-0be9-4c02-9d30-d362de4260f7', max_length=100, verbose_name='Nome Compra'),
        ),
        migrations.AlterField(
            model_name='solicitacao_venda',
            name='nome_venda',
            field=models.CharField(default='adf14f13-b703-4d55-a665-dd5d61b8f70d', max_length=100, verbose_name='Nome Venda'),
        ),
        migrations.AlterField(
            model_name='solicitacao_venda',
            name='status_venda',
            field=models.CharField(choices=[('waiting', 'Solicitado'), ('done', 'Vendido'), ('canceled', 'Cancelado')], default=('waiting', 'Solicitado'), max_length=100, verbose_name='Status'),
        ),
    ]
