# Generated by Django 4.0.4 on 2022-05-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_solicitacao_compra_nome_compra_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitacao_venda',
            old_name='moeda_venda',
            new_name='posse',
        ),
        migrations.AlterField(
            model_name='solicitacao_compra',
            name='nome_compra',
            field=models.CharField(default='46af22e3-ae69-4790-a798-6301a9e54097', max_length=100, verbose_name='Nome Compra'),
        ),
        migrations.AlterField(
            model_name='solicitacao_venda',
            name='nome_venda',
            field=models.CharField(default='10e89320-8fa2-4ca2-b775-7cb49f1c0b89', max_length=100, verbose_name='Nome Venda'),
        ),
    ]
