# Generated by Django 4.0.4 on 2022-05-01 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_moeda_venda_solicitacao_venda_posse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao_compra',
            name='nome_compra',
            field=models.CharField(default='12470c59-7943-4c50-8c10-fc3def495049', max_length=100, verbose_name='Nome Compra'),
        ),
        migrations.AlterField(
            model_name='solicitacao_venda',
            name='nome_venda',
            field=models.CharField(default='72a7fa07-b9d6-4675-8a2a-5ca5b0f3020a', max_length=100, verbose_name='Nome Venda'),
        ),
        migrations.AlterField(
            model_name='solicitacao_venda',
            name='posse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.moeda_usuario', verbose_name='Posse Escolhida'),
        ),
    ]
