# Generated by Django 4.0.4 on 2022-05-02 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_solicitacao_compra_nome_compra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moeda_usuario',
            name='status',
            field=models.CharField(choices=[('active', 'Ativo na Conta'), ('waiting', 'Venda Solicitada'), ('sold', 'Vendido'), ('refunded', 'Reembolsado')], default='active', max_length=100, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='solicitacao_compra',
            name='nome_compra',
            field=models.CharField(default='90f9035a-c68b-4d0c-926d-8c608682c4ce', max_length=100, verbose_name='Nome Compra'),
        ),
        migrations.AlterField(
            model_name='solicitacao_venda',
            name='nome_venda',
            field=models.CharField(default='ca6ebc0b-f4b4-4155-ac8a-a5500cbb4093', max_length=100, verbose_name='Nome Venda'),
        ),
        migrations.AlterField(
            model_name='solicitacao_venda',
            name='status_venda',
            field=models.CharField(choices=[('waiting', 'Solicitado'), ('done', 'Vendido'), ('canceled', 'Cancelado')], default='waiting', max_length=100, verbose_name='Status'),
        ),
    ]
