# Generated by Django 4.0.4 on 2022-05-02 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_moeda_usuario_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao_compra',
            name='nome_compra',
            field=models.CharField(default='ddb0883b-b7df-49db-8b24-51056d84427e', max_length=100, verbose_name='Nome Compra'),
        ),
        migrations.AlterField(
            model_name='solicitacao_venda',
            name='nome_venda',
            field=models.CharField(default='590f5c41-f4b1-4544-bba9-2af99fd8a486', max_length=100, verbose_name='Nome Venda'),
        ),
    ]
