# Generated by Django 4.0.4 on 2022-05-02 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_solicitacao_compra_nome_compra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao_compra',
            name='nome_compra',
            field=models.CharField(default='6fc41331-adda-4c1d-8461-57a1e83e53da', editable=False, max_length=100, verbose_name='Nome Compra'),
        ),
        migrations.AlterField(
            model_name='solicitacao_venda',
            name='nome_venda',
            field=models.CharField(default='2897b4f3-022c-4fd0-b516-b8a890aead14', max_length=100, verbose_name='Nome Venda'),
        ),
    ]
