# Generated by Django 4.0.4 on 2022-05-03 13:11

import cpf_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusuario',
            name='cpf',
            field=cpf_field.models.CPFField(max_length=11, unique=True, verbose_name='cpf'),
        ),
    ]
